### PR TITLE
chore: upgrade deps, fix tests

### PR DESCRIPTION
**Pull request by tomholford**
# Context

Currently, checking out the `main` branch, installing deps, and running the tests fails. This PR updates the deps and fixes one of the tests.

# Changes

- [x] upgrade `dappwright` to `2.8.0`
- [x] peg node to 16
- [x] fix `single-test` case
- [x] fix `multiple-files` case

In a future PR:
- [ ] fix `multiple-wallets` case

# Status

## Single Test

image

## Multiple Files

<details>
<summary>click to expand</summary>
image
</details>

## Multiple Wallets

image

### CODE REVIEW

**Comment by tomholford** [comment]
@osis Thanks for sharing this cool project. I brought the example repo deps up to date and fixed one of the tests. Hope this helps

**Comment by osis** [comment]
thanks a bunch, this all looks great! Let me take a quick look and get this merged.

**Review by osis — APPROVED** [review]

**Comment by osis** [comment]
There is some behaviour that seems to have changed at the playwright level. Working through them and will let you know.

**Comment by osis** [comment]
This adjustment seems to fix the first issue.
```javascript
  const networkStatus = page.getByTestId("network-status");
  expect(await networkStatus.inputValue()).toEqual("31337")
```

This download error is a bit of a known issue on the dappwright side. If you retry, it should be okay.

**Comment by osis** [comment]
Taking a look at the other error, that's the only suggestion I would make. There is one other issue where the tests timeout clicking the connect button when for Coinbase, but that's an external issue that I'm not sure we can mitigate atm.

**Comment by tomholford** [comment]
> This adjustment seems to fix the first issue.
> 
> ```js
>   const networkStatus = page.getByTestId("network-status");
>   expect(await networkStatus.inputValue()).toEqual("31337")
> ```
> 
> This download error is a bit of a known issue on the dappwright side. If you retry, it should be okay.

@osis Thanks for the tip. Just pushed a commit with this change. It fixed all the tests except for the Coinbase wallet case. Given that this is expected, I think this is now good for merge.

**Comment by osis** [comment]
Awesome. Looks great!

**Pull request merged**
